<?php
/**
 * BusinessManagementApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  WhatsAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace WhatsAPI\Test\Api;

use \WhatsAPI\Configuration;
use \WhatsAPI\ApiException;
use \WhatsAPI\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * BusinessManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  WhatsAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BusinessManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for instancesInstanceKeyBusinessCatalogGet
     *
     * Fetches the catlog..
     *
     */
    public function testInstancesInstanceKeyBusinessCatalogGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
