<?php
/**
 * GroupManagementApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GroupManagementApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GroupManagementApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for instancesInstanceKeyGroupsAdminGet
     *
     * Get admin groupss..
     *
     */
    public function testInstancesInstanceKeyGroupsAdminGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsCreatePost
     *
     * Create group..
     *
     */
    public function testInstancesInstanceKeyGroupsCreatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGet
     *
     * Get all groups..
     *
     */
    public function testInstancesInstanceKeyGroupsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdAnnouncePut
     *
     * Set group announce..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdAnnouncePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdDelete
     *
     * Leaves the group..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdDescriptionPut
     *
     * Set group description..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdDescriptionPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdGet
     *
     * Get group..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdInviteCodeGet
     *
     * Get group invite code..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdInviteCodeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdLockPut
     *
     * Set group locked..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdLockPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdNamePut
     *
     * Set group name..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdNamePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdParticipantsAddPost
     *
     * Add participant..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdParticipantsAddPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdParticipantsDemotePut
     *
     * Demote participant..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdParticipantsDemotePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdParticipantsPromotePut
     *
     * Promote participant..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdParticipantsPromotePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdParticipantsRemoveDelete
     *
     * Remove participant..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdParticipantsRemoveDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsGroupIdProfilePicPut
     *
     * Set group picture..
     *
     */
    public function testInstancesInstanceKeyGroupsGroupIdProfilePicPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGroupsInviteInfoGet
     *
     * Get group from invite link..
     *
     */
    public function testInstancesInstanceKeyGroupsInviteInfoGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
