<?php
/**
 * InstanceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InstanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InstanceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for instancesCreateGet
     *
     * Creates a new instance key..
     *
     */
    public function testInstancesCreateGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyContactsGet
     *
     * Get contacts..
     *
     */
    public function testInstancesInstanceKeyContactsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyDeleteDelete
     *
     * Delete Instance..
     *
     */
    public function testInstancesInstanceKeyDeleteDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyGet
     *
     * Get Instance..
     *
     */
    public function testInstancesInstanceKeyGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyLogoutDelete
     *
     * Logout Instance..
     *
     */
    public function testInstancesInstanceKeyLogoutDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyQrcodeGet
     *
     * Get QrCode..
     *
     */
    public function testInstancesInstanceKeyQrcodeGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeyWebhookPut
     *
     * Change Webhook url..
     *
     */
    public function testInstancesInstanceKeyWebhookPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesListGet
     *
     * Get all instances..
     *
     */
    public function testInstancesListGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
