<?php
/**
 * MessageSendingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * WhatsAPI Go
 *
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MessageSendingApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MessageSendingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for instancesInstanceKeyBusinessCatalogGet
     *
     * Fetches the catlog..
     *
     */
    public function testInstancesInstanceKeyBusinessCatalogGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendAudioPost
     *
     * Send raw audio..
     *
     */
    public function testInstancesInstanceKeySendAudioPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendButtonMediaPost
     *
     * Send a button message with a media header..
     *
     */
    public function testInstancesInstanceKeySendButtonMediaPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendButtonsPost
     *
     * Send a button message..
     *
     */
    public function testInstancesInstanceKeySendButtonsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendContactPost
     *
     * Send a contact message..
     *
     */
    public function testInstancesInstanceKeySendContactPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendDocumentPost
     *
     * Send raw document..
     *
     */
    public function testInstancesInstanceKeySendDocumentPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendImagePost
     *
     * Send raw image..
     *
     */
    public function testInstancesInstanceKeySendImagePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendListPost
     *
     * Send a List message..
     *
     */
    public function testInstancesInstanceKeySendListPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendLocationPost
     *
     * Send a location message..
     *
     */
    public function testInstancesInstanceKeySendLocationPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendMediaPost
     *
     * Send a media message..
     *
     */
    public function testInstancesInstanceKeySendMediaPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendPollPost
     *
     * Send a Poll message with media..
     *
     */
    public function testInstancesInstanceKeySendPollPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendTemplateMediaPost
     *
     * Send a template message with media..
     *
     */
    public function testInstancesInstanceKeySendTemplateMediaPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendTemplatePost
     *
     * Send a template message..
     *
     */
    public function testInstancesInstanceKeySendTemplatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendTextPost
     *
     * Send a text message..
     *
     */
    public function testInstancesInstanceKeySendTextPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendUploadPost
     *
     * Upload media..
     *
     */
    public function testInstancesInstanceKeySendUploadPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for instancesInstanceKeySendVideoPost
     *
     * Send raw video..
     *
     */
    public function testInstancesInstanceKeySendVideoPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
